name: Build Spigot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run BuildTools
        run: java -jar BuildTools.jar --rev 1.21

      - name: Archive generated jar
        uses: actions/upload-artifact@v2
        with:
          name: spigot-1.21
          path: ./spigot-1.21.jar
